# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPaymen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddPay(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 430)
        self.pb_add_pay1 = QtWidgets.QPushButton(Form)
        self.pb_add_pay1.setGeometry(QtCore.QRect(30, 340, 210, 26))
        self.pb_add_pay1.setObjectName("pb_add_pay1")
        self.pushButton_cansel1 = QtWidgets.QPushButton(Form)
        self.pushButton_cansel1.setGeometry(QtCore.QRect(30, 380, 211, 26))
        self.pushButton_cansel1.setObjectName("pushButton_cansel1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 0, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(120, 120, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 180, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 250, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_reporting_period = QtWidgets.QLineEdit(Form)
        self.lineEdit_reporting_period.setGeometry(QtCore.QRect(10, 30, 260, 26))
        self.lineEdit_reporting_period.setObjectName("lineEdit_reporting_period")
        self.lineEdit_4_cost = QtWidgets.QLineEdit(Form)
        self.lineEdit_4_cost.setGeometry(QtCore.QRect(10, 90, 260, 26))
        self.lineEdit_4_cost.setObjectName("lineEdit_4_cost")
        self.lineEdit_debt = QtWidgets.QLineEdit(Form)
        self.lineEdit_debt.setGeometry(QtCore.QRect(10, 150, 260, 26))
        self.lineEdit_debt.setObjectName("lineEdit_debt")
        self.lineEdit_data_pay = QtWidgets.QLineEdit(Form)
        self.lineEdit_data_pay.setGeometry(QtCore.QRect(10, 220, 260, 26))
        self.lineEdit_data_pay.setObjectName("lineEdit_data_pay")
        self.lineEdit_amount_paid = QtWidgets.QLineEdit(Form)
        self.lineEdit_amount_paid.setGeometry(QtCore.QRect(10, 290, 260, 26))
        self.lineEdit_amount_paid.setObjectName("lineEdit_amount_paid")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", " Добавление данных "))
        self.pb_add_pay1.setText(_translate("Form", "добавить"))
        self.pushButton_cansel1.setText(_translate("Form", "отмена "))
        self.label_3.setText(_translate("Form", "отчетный период "))
        self.label_4.setText(_translate("Form", "стоимость "))
        self.label_5.setText(_translate("Form", "долг"))
        self.label_6.setText(_translate("Form", "дата оплаты "))
        self.label_7.setText(_translate("Form", "оплаченная сумма "))
