# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deleteflat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Deleteflat(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 129)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 430, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pb_yes_flat = QtWidgets.QPushButton(Form)
        self.pb_yes_flat.setGeometry(QtCore.QRect(30, 70, 80, 26))
        self.pb_yes_flat.setObjectName("pb_yes_flat")
        self.pushButton_no_flat = QtWidgets.QPushButton(Form)
        self.pushButton_no_flat.setGeometry(QtCore.QRect(290, 70, 80, 26))
        self.pushButton_no_flat.setObjectName("pushButton_no_flat")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Вы хотите удалить строчку ?"))
        self.pb_yes_flat.setText(_translate("Form", "да"))
        self.pushButton_no_flat.setText(_translate("Form", "нет"))
