# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteresident.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Deleteresident(QtWidgets.QWidget):
    def setupUi(self, delete_resit):
        delete_resit.setObjectName("delete_resit")
        delete_resit.resize(485, 125)
        self.pushButton_yes_residents = QtWidgets.QPushButton(delete_resit)
        self.pushButton_yes_residents.setGeometry(QtCore.QRect(40, 70, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_yes_residents.setFont(font)
        self.pushButton_yes_residents.setObjectName("pushButton_yes_residents")
        self.pushButton_no_residents = QtWidgets.QPushButton(delete_resit)
        self.pushButton_no_residents.setGeometry(QtCore.QRect(380, 70, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_no_residents.setFont(font)
        self.pushButton_no_residents.setObjectName("pushButton_no_residents")
        self.label_resident = QtWidgets.QLabel(delete_resit)
        self.label_resident.setGeometry(QtCore.QRect(20, 10, 410, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_resident.setFont(font)
        self.label_resident.setObjectName("label_resident")

        self.retranslateUi(delete_resit)
        QtCore.QMetaObject.connectSlotsByName(delete_resit)

    def retranslateUi(self, delete_resit):
        _translate = QtCore.QCoreApplication.translate
        delete_resit.setWindowTitle(_translate("delete_resit", "удаление данных "))
        self.pushButton_yes_residents.setText(_translate("delete_resit", "да"))
        self.pushButton_no_residents.setText(_translate("delete_resit", "нет"))
        self.label_resident.setText(_translate("delete_resit", "Вы хотите удалить это строчку?"))
