# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'residentadd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddResident(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(362, 259)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 281, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 271, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(60, 140, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_fio_rt = QtWidgets.QLineEdit(Form)
        self.lineEdit_fio_rt.setGeometry(QtCore.QRect(20, 40, 310, 30))
        self.lineEdit_fio_rt.setObjectName("lineEdit_fio_rt")
        self.lineEdit_pasport_data = QtWidgets.QLineEdit(Form)
        self.lineEdit_pasport_data.setGeometry(QtCore.QRect(20, 110, 310, 30))
        self.lineEdit_pasport_data.setObjectName("lineEdit_pasport_data")
        self.lineEdit_data_bitch = QtWidgets.QLineEdit(Form)
        self.lineEdit_data_bitch.setGeometry(QtCore.QRect(20, 180, 310, 30))
        self.lineEdit_data_bitch.setObjectName("lineEdit_data_bitch")
        self.pb_add_resident = QtWidgets.QPushButton(Form)
        self.pb_add_resident.setGeometry(QtCore.QRect(50, 220, 75, 23))
        self.pb_add_resident.setObjectName("pb_add_resident")
        self.pushButton_cl_resident = QtWidgets.QPushButton(Form)
        self.pushButton_cl_resident.setGeometry(QtCore.QRect(220, 220, 75, 23))
        self.pushButton_cl_resident.setObjectName("pushButton_cl_resident")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "добавление данных проживающих"))
        self.label_3.setText(_translate("Form", "ФИО проживающего"))
        self.label_4.setText(_translate("Form", "паспортные данных "))
        self.label_5.setText(_translate("Form", "дата рождения "))
        self.pb_add_resident.setText(_translate("Form", "добавить"))
        self.pushButton_cl_resident.setText(_translate("Form", "отмена"))
