# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 160, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_add_reporting_period = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_reporting_period.setGeometry(QtCore.QRect(40, 40, 250, 31))
        self.lineEdit_add_reporting_period.setText("")
        self.lineEdit_add_reporting_period.setObjectName("lineEdit_add_reporting_period")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2_add_cost = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2_add_cost.setGeometry(QtCore.QRect(40, 100, 250, 30))
        self.lineEdit_2_add_cost.setText("")
        self.lineEdit_2_add_cost.setObjectName("lineEdit_2_add_cost")
        self.pushButton_add_Pay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_Pay.setGeometry(QtCore.QRect(100, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_add_Pay.setFont(font)
        self.pushButton_add_Pay.setObjectName("pushButton_add_Pay")
        self.pushButton_exit_Pay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit_Pay.setGeometry(QtCore.QRect(100, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_exit_Pay.setFont(font)
        self.pushButton_exit_Pay.setObjectName("pushButton_exit_Pay")
        self.lineEdit_add_debt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_debt.setGeometry(QtCore.QRect(40, 160, 250, 31))
        self.lineEdit_add_debt.setText("")
        self.lineEdit_add_debt.setObjectName("lineEdit_add_debt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 120, 40, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_add_amount_paid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_amount_paid.setGeometry(QtCore.QRect(40, 290, 250, 31))
        self.lineEdit_add_amount_paid.setText("")
        self.lineEdit_add_amount_paid.setObjectName("lineEdit_add_amount_paid")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 250, 170, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.dateEdit_data_payment = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_data_payment.setGeometry(QtCore.QRect(70, 220, 130, 27))
        self.dateEdit_data_payment.setObjectName("dateEdit_data_payment")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Отчетный период"))
        self.label_2.setText(_translate("MainWindow", "Стоимость"))
        self.pushButton_add_Pay.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit_Pay.setText(_translate("MainWindow", "Отмена"))
        self.label_3.setText(_translate("MainWindow", "Долг"))
        self.label_4.setText(_translate("MainWindow", "дата оплаты "))
        self.label_5.setText(_translate("MainWindow", "оплаченная сумма"))
