# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_flat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_add_Flat_square = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_Flat_square.setGeometry(QtCore.QRect(20, 50, 221, 31))
        self.lineEdit_add_Flat_square.setObjectName("lineEdit_add_Flat_square")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2_add_Flat_quanity_resident = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2_add_Flat_quanity_resident.setGeometry(QtCore.QRect(20, 110, 221, 31))
        self.lineEdit_2_add_Flat_quanity_resident.setObjectName("lineEdit_2_add_Flat_quanity_resident")
        self.pushButton_add_base_Flat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_base_Flat.setGeometry(QtCore.QRect(60, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_add_base_Flat.setFont(font)
        self.pushButton_add_base_Flat.setObjectName("pushButton_add_base_Flat")
        self.pushButton_exit_Flat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit_Flat.setGeometry(QtCore.QRect(60, 340, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_exit_Flat.setFont(font)
        self.pushButton_exit_Flat.setObjectName("pushButton_exit_Flat")
        self.lineEdit_add_availability_benefits = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_availability_benefits.setGeometry(QtCore.QRect(20, 170, 221, 31))
        self.lineEdit_add_availability_benefits.setObjectName("lineEdit_add_availability_benefits")
        self.lineEdit_add_Flat_adress = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_Flat_adress.setGeometry(QtCore.QRect(20, 240, 220, 31))
        self.lineEdit_add_Flat_adress.setObjectName("lineEdit_add_Flat_adress")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 210, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Площадь квартиры"))
        self.label_2.setText(_translate("MainWindow", "Количество проживающих"))
        self.pushButton_add_base_Flat.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit_Flat.setText(_translate("MainWindow", "Отмена"))
        self.label_3.setText(_translate("MainWindow", "Наличие льготы"))
        self.label_4.setText(_translate("MainWindow", "Адрес"))
