# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_resident.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(273, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_add_resident_adreess = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_resident_adreess.setGeometry(QtCore.QRect(20, 50, 221, 31))
        self.lineEdit_add_resident_adreess.setObjectName("lineEdit_add_resident_adreess")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2_add_Resident_fio_resident = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2_add_Resident_fio_resident.setGeometry(QtCore.QRect(20, 110, 221, 31))
        self.lineEdit_2_add_Resident_fio_resident.setObjectName("lineEdit_2_add_Resident_fio_resident")
        self.pushButton_add_base_Resident = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_base_Resident.setGeometry(QtCore.QRect(60, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_add_base_Resident.setFont(font)
        self.pushButton_add_base_Resident.setObjectName("pushButton_add_base_Resident")
        self.pushButton_exit_Resident = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit_Resident.setGeometry(QtCore.QRect(60, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_exit_Resident.setFont(font)
        self.pushButton_exit_Resident.setObjectName("pushButton_exit_Resident")
        self.lineEdit_add_resident_pasport_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_resident_pasport_data.setGeometry(QtCore.QRect(20, 170, 221, 31))
        self.lineEdit_add_resident_pasport_data.setObjectName("lineEdit_add_resident_pasport_data")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 210, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dateEdit_date_nitch = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_date_nitch.setGeometry(QtCore.QRect(20, 240, 170, 30))
        self.dateEdit_date_nitch.setObjectName("dateEdit_date_nitch")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Адресс"))
        self.label_2.setText(_translate("MainWindow", "ФИО проживающего"))
        self.pushButton_add_base_Resident.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_exit_Resident.setText(_translate("MainWindow", "Отмена"))
        self.label_3.setText(_translate("MainWindow", "Паспортные данных"))
        self.label_4.setText(_translate("MainWindow", "Дата рождения "))
