# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteFlat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 130)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 260, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_yes_flat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yes_flat.setGeometry(QtCore.QRect(40, 70, 80, 26))
        self.pushButton_yes_flat.setObjectName("pushButton_yes_flat")
        self.pushButton_no_flat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_no_flat.setGeometry(QtCore.QRect(250, 70, 80, 26))
        self.pushButton_no_flat.setObjectName("pushButton_no_flat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Вы хотите удалить?"))
        self.pushButton_yes_flat.setText(_translate("MainWindow", "да "))
        self.pushButton_no_flat.setText(_translate("MainWindow", "нет"))
